# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US
reviews:
  request_changes_workflow: true
  auto_title_placeholder: "@coderabbitai"
  auto_review:
    enabled: true
    drafts: false
integrations:
  github:
    auto_merge: true
    enable_auto_merge: true
